FROM adoptopenjdk/openjdk11:jre-11.0.6_10-alpine
MAINTAINER digiplay
COPY target/digiplay-auth-service-0.0.1-SNAPSHOT.jar digiplay-auth-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/digiplay-auth-service-0.0.1-SNAPSHOT.jar"]