# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auth-service CI

on:
  push:
    branches: [ main ]
    paths:
    - 'digiplay-auth-service/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'digiplay-auth-service/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTH }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file digiplay-auth-service/pom.xml -Dsonar.projectKey=com.example:digiplay-auth-service
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: 'Push and deploy'
      run: |
        cd digiplay-auth-service/
        mvn clean -B package --file ./pom.xml
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker build -t europe-west1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/digiplay-repo/digiplay-auth-service:v10 .
        docker push europe-west1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/digiplay-repo/digiplay-auth-service:v10
        gcloud container clusters get-credentials digiplay-cluster --zone europe-west1-b
        sleep 5s
        kubectl set image deployment/digiplay-auth-service digiplay-auth-service-sha256-1=europe-west1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/digiplay-repo/digiplay-auth-service:v10
        sleep 5s
        kubectl get nodes
